version: '3.8'
services:

  eureka-server:
    image: lukasz94w/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway-service:
    image: lukasz94w/api-gateway-service:latest
    container_name: api-gateway-service
    ports:
      - "8081:8080"
    expose:
      - "8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
    volumes:
      - ./apps-log:/log
    depends_on:
      - eureka-server

  auth-service-redis:
    image: redis:7.2.4
    container_name: auth-service-redis
    volumes:
      - ./auth-service-redis/session-data:/var/lib/redis

  auth-service:
    image: lukasz94w/auth-service:latest
    container_name: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./apps-log:/log
    depends_on:
      - api-gateway-service
      - eureka-server
      - auth-service-redis

  game-server-core:
    image: lukasz94w/game-server-core:latest
    container_name: game-server-core
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./apps-log:/log
    depends_on:
      - api-gateway-service
      - eureka-server

  history-service-mariadb:
    image: mariadb:11.4.1-rc
    container_name: history-service-mariadb
    restart: always
    environment:
      MARIADB_DATABASE: database
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./history-service-mariadb/history-data:/var/lib/mysql

  history-service:
    image: lukasz94w/history-service:latest
    container_name: history-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./apps-log:/log
    depends_on:
      - api-gateway-service
      - eureka-server
      - history-service-mariadb