server:
  port: 8081

spring:
  application:
    name: api-gateway-service
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - OPTIONS


